[theme]
primaryColor = "#0284C7"
backgroundColor = "#020617"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
